### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by YoungDeveloper1** [abdibrokhim/humanaize#1]
This is the error message I get when I try using this code from [the hosted subdomain.](https://humanaize.vercel.app/) 
![image](https://github.com/user-attachments/assets/b719c3d3-3b99-43c1-b312-67c8f2939b21)

**Comment by abdibrokhim** [comment]
hello, there! did you follow this https://github.com/abdibrokhim/humanaize?tab=readme-ov-file#-run-locally ?

**Comment by YoungDeveloper1** [comment]
Sorry, I haven't tried running it locally. I only pasted gpt generated text
on your subdomain. I am trying to go local right now. And I must say that
you are not just cool but also special!

**Comment by abdibrokhim** [comment]
ohh, i seee the issue. will fix it)))

**Comment by YoungDeveloper1** [comment]
Thank you so much

**Comment by abdibrokhim** [comment]
there is an issue with ai ml api. i just send request to gpt via openai api not ai/ml api.

<img width="669" alt="Screenshot 2024-12-19 at 17 43 40" src="https://github.com/user-attachments/assets/5259ff80-f575-40ba-932c-76e0ce14816e" />

**Comment by YoungDeveloper1** [comment]
Yes sure, I suspected such an issue with the api.
